== 第三周第二天
. 继承和消息

     继承允许你创建一个类，作为另一个类的精炼（refinement）和特化（specialization）。

     "< Song" 是告诉Ruby, KaraokeSong是Song 的子类（subclass）

     to_s方法:所定义的任何类的实例应该有一个 to_s 方法返回一个字符串形式表示对象

     Ruby支持单继承，但它提供了mixin(method)它提供了多继承的许多特征。一个mixin是一种"模块"类型

      (不带参数)super的用法比较灵活, 使用super的时候, 如果不带任何参数(也没有括号), 实际上的作用是自动调用父类中的当前方法, 并且把当前参数也传过去

     （super后带参数）super 父类方法的参数和子类不一样, 才需要显式的传入参数调用

. 对象和属性

     initialize方法是一个标准的Ruby类的方法，和其它面向对象编程语言的构造方法有相同的方式工作。 initialize方法是有用的，在创建对象的时候，一些类变量初始化。这种方法可能需要的参数列表，它像其他Ruby之前的方法用def关键字定义

     实例变量是类的一种属性，一旦我们使用的类对象被创建的对象的属性。每个对象的属性被分别赋值的并与其它对象共享，它们在类的内部使用@操作符访问，但访问类之外的，我们使用的公共方法被称为访问器方法

. 类变量和类方法

     类变量是一个变量，这是一个类的所有实例之间共享。该变量是一个实例，它是可访问对象实例。两个@字符类变量带有前缀（@@）。在类定义类变量必须初始化

     def self.methodname() 以 end 字符结束，将被称为使用classname.methodname类名

.  访问控制

      Public Methods: 任何人都可以被称为public方法。方法默认为公用初始化，这始终是 private 除外。 .

      Private Methods: private方法不能被访问，或者甚至从类的外部浏览。只有类方法可以访问私有成员。

      Protected Methods: 受保护的方法可以被调用，只能通过定义类及其子类的对象。访问保存在类内部。

. 变量

     变量用来保存这些对象的印迹；每个变量保存一个底下那个的引用。

        person = "Tim" => "Tim"
        person.object_id => 16777380
        person.class => String
        person => "Tim"
