== 第三周第三天

=== 容器
 . 数组: Ruby的数组是有序的，任何对象的整数索引的集合。数组中的每个元素与指数。数组索引从0开始。负指数假设数组的末尾---是，指数为-1表示最后一个元素，-2是数组中的最后一个元素.
  Ruby的数组能容纳的对象，如字符串，整数，Fixnum对象，哈希，符号，甚至其他的Array对象。 Ruby的数组自动增长，同时增加他们的元素.

 Array:
        a = [ 3.14159, "pie", 99] => [3.14159, "pie", 99]
        a.class => Array
        a.length => 3
        a[0] => 3.14159
        a[1] => "pie"
        a[2] => 99
        a[3] => nil

        b = Array.new
        b.class  => Array
        b.length => 0
        b[0] = "second" => second
        b[1] = "array"  => array
        b   => ["second", "array"]

 . 散列表:散列表通过键（key）来访问，支持以任何对象作为它的键。
      散列表字面量（hash literal）使用花括号而不是方括号。这个字面量必须为每一项提供两个对象：一个键（key）和一个值（value）。

    Hash字幕符号表示法：处于花括号之间的key => value配对的列表

=== Blocks和迭代器

  . 迭代器： 在代码中只和方法调用一起出现，block和方法调用的最后一个参数处于同一行，并紧跟在其后（或者参数列表的右括号的后面）。
      在遇到block的时候并不立刻执行其中的代码。ruby会记住block出现是的上下文（局部变量，当前对象等）然后执行方法调用。
      在方法内部，block可以像方法一样被yield语句调用，每执行一次yield，就会调用block中的代码。当block执行结束时，控制返回到紧随yield之后的那条语句。

 def fib_up_to(max)
  i1,i2 = 1,1
  while i1 <= max
    yield i1
    i1,i2 = i2,i1+i2
  end
 end
 fib_up_to(1000) {|f| print f, " " }
 => 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987

    两个简单的迭代器each和collect。each可以认为是最简单的迭代器，它会对集合的每个元素调用块。 collect，将容器中的元素传递给一个块，在块中处理后返回一个包含处理结果的新数组。

   迭代器的功能就是一种回调！迭代器方法所属的类只负责遍历需要遍历的元素，而对元素所做的处理则通过回调代码块来实现

  . Block

  代码块(Blocks)是指一块代码，用大括号({})或者do…end来标明起始和结束，代码块只能跟在方法调用后边。

   yield语句：在方法内部使用yield语句来占位，当方法执行到yield时，实际执行的是调用方法时跟在后边的的代码块。

  |x|：变量用一对’|’包裹，在代码块中使用，用于接受yield传递的参数。yield后跟的参数会传递给代码块中用| |标志的变量


NOTE: 如果方法的最后一个参数前带有 &，那么你可以向该方法传递一个块，且这个块可被赋给最后一个参数。如果 * 和 & 同时出现在参数列表中，& 应放在后面。
def test(&block)
 block.call
 end
test { puts "Hello World!"}
=>Hello World!

=== BEGIN 和 END 块
      每个 Ruby 源文件可以声明当文件被加载时要运行的代码块（BEGIN 块），以及程序完成执行后要运行的代码块（END 块）。
      一个程序可以包含多个 BEGIN 和 END 块。BEGIN 块按照它们出现的顺序执行。END 块按照它们出现的相反顺序执行

      BEGIN { puts "BEGIN 代码块"}
      END { puts "END 代码块"}
      puts "MAIN 代码块"
      =>BEGIN 代码块
        MAIN 代码块
        END 代码块
