== 第四周第一天

  TDD：测试驱动开发（Test-Driven Development）
测试驱动开发是敏捷开发中的一项核心实践和技术，也是一种设计方法论。TDD的原理是在开发功能代码之前，先编写单元测试用例代码，测试代码确定需要编写什么产品代码。TDD的基本思路就是通过测试来推动整个开发的进行，但测试驱动开发并不只是单纯的测试工作，而是把需求分析，设计，质量控制量化的过程。TDD首先考虑使用需求（对象、功能、过程、接口等），主要是编写测试用例框架对功能的过程和接口进行设计，而测试框架可以持续进行验证。

  BDD：行为驱动开发（Behavior Driven Development）
行为驱动开发是一种敏捷软件开发的技术，它鼓励软件项目中的开发者、QA和非技术人员或商业参与者之间的协作。主要是从用户的需求出发，强调系统行为。BDD最初是由Dan North在2003年命名，它包括验收测试和客户测试驱动等的极限编程的实践，作为对测试驱动开发的回应。

  ATDD：验收测试驱动开发（Acceptance Test Driven Development）
TDD 只是开发人员的职责，通过单元测试用例来驱动功能代码的实现。在准备实施一个功能或特性之前，首先团队需要定义出期望的质量标准和验收细则，以明确而且达成共识的验收测试计划（包含一系列测试场景）来驱动开发人员的TDD实践和测试人员的测试脚本开发。面向开发人员，强调如何实现系统以及如何检验。

 . 数字

 3.times {print "x "}
 1.upto(5) {|i| print i, " "}
 99.downto(95) {|i| print i, " "}
 50.step(80,5) {|i| print i, " "}
 => x x x 1 2 3 4 5 99 98 97 96 95 50 55 60 65 70 75 80

 . 字符串

    Ruby字符串文字包含在单引号和双引号内。

    在Ruby语言中编写多行字符串非常简单。下面是显示打印多行字符串的三种方式。
     1.字符串可以写在双引号内。
     2.使用％字符，字符串包含在/字符内。
     3.在heredoc语法中，使用<<并且字符串包含在单词STRING内。

    - 连接字符串

    Ruby连接字符串是要使用多个字符串来创建一个字符串。可以通过连接多个字符串来形成单个字符串。

    将Ruby字符串连接成单个字符串有四种方法：
      在每个字符串之间使用加(+)号。
      在每个字符串之间使用单个空格。
      在每个字符串之间使用<<符号。
      在字符串之间使用concat方法。

      string = "This is Ruby Tutorial" + " from Yiibai." + " Wish you all good luck."
       puts string

       string = "This is Ruby Tutorial" " from Yiibai." " Wish you all good luck."
       puts string

       string = "This is Ruby Tutorial" << " from Yiibai." << " Wish you all good luck."
        puts string

      string = "This is Ruby Tutorial".concat(" from Yiibai.").concat(" Wish you all good luck.")
        puts string

    . 区间

    ruby使用区间去实现3种不同的特性：序列，条件和间隔。

    - 表达序列： 序列有起点，终点以及在序列中产生连续值的方法。在Ruby中，使用“..”和“...”区间操作符来创建序列。两个点的形式是创建闭合的区间（包括右端的值），而3个点的形式是创建半闭半开的区间（不包括右端的值）

       1..10
       'a'..'z'
       my_array = [ 1,2,3 ]
       0...my_array.length

    - 条件表达式：在这里他们表现得就像某种双向开关——当区间第一部分的条件为 true 时，他们就打开，当区间第二部分的条件为 true 时，他们就关闭。

    while line = gets
      puts line if line =~ /start/ .. line =~ /end/
    end

    - 间隔测试：看看一些值是否会落入区间表达的间隔内。使用===即case

        (1..10)     === 5   => true
        (1..10)     === 15  => false

    . 正则表达式：正则表达式被用来根据模式对字符串进行匹配。Ruby提供了內建的支持，使得模式匹配和替换变得更方便和更简明。

      正则表达式是 Regexp 类型的对象。可以通过显式地调用构造函数或使用字面量形式/pattern/和%r{pattern}来创建他们。

       a = Regexp.new('^\s*[a-z]')
       b = /^\s*[a-z]/               =>/^\s*[a-z]/
       c = %r{^\s*[a-z]}

    . 模式： 每个正则表达式包含一种模式，用来对字符串进行正则表达式的匹配。
